{{- if has "feature-complete" .Values.profiles }}
{{- $redisHost := include "sentry.redis.host" . -}}
{{- $redisPort := include "sentry.redis.port" . -}}
{{- $redisPass := include "sentry.redis.password" . -}}
{{- $redisDb     := include "sentry.redis.db" . -}}
{{- $redisProto  := ternary "rediss" "redis" (eq (include "sentry.redis.ssl" .) "true")  -}}
{{- if .Values.uptimeChecker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-uptime-checker
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: uptime-checker
{{- if not .Values.uptimeChecker.autoscaling.enabled }}
  replicas: {{ .Values.uptimeChecker.replicas }}
{{- end }}
  template:
    metadata:
      {{- if .Values.uptimeChecker.annotations }}
      annotations:
{{ toYaml .Values.uptimeChecker.annotations | indent 8 }}
      {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: uptime-checker
        {{- if .Values.uptimeChecker.podLabels }}
{{ toYaml .Values.uptimeChecker.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.uptimeChecker.affinity }}
{{ toYaml .Values.uptimeChecker.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.uptimeChecker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.uptimeChecker.nodeSelector | indent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.uptimeChecker.tolerations }}
      tolerations:
{{ toYaml .Values.uptimeChecker.tolerations | indent 8 }}
      {{- else if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.uptimeChecker.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.uptimeChecker.topologySpreadConstraints | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.uptimeChecker.securityContext }}
      securityContext:
{{ toYaml .Values.uptimeChecker.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-uptime-checker
        image: "{{ template "uptimeChecker.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.uptimeChecker.pullPolicy }}
        args:
          - run
        env:
          - name: UPTIME_CHECKER_RESULTS_KAFKA_CLUSTER
            value: {{ include "sentry.kafka.host" . }}:{{ include "sentry.kafka.port" . }}
          - name: UPTIME_CHECKER_REDIS_HOST
            value: {{ if $redisPass -}}
              {{ $redisProto }}://:{{ $redisPass }}@{{ $redisHost }}:{{ $redisPort }}/{{ $redisDb }}
            {{ else if and (not .Values.externalRedis.existingSecret) (not .Values.redis.auth.existingSecret) -}}
              {{ $redisProto }}://{{ $redisHost }}:{{ $redisPort }}/{{ $redisDb }}
            {{- end }}
          - name: UPTIME_CHECKER_ALLOW_INTERNAL_IPS
            value: "false"
          - name: UPTIME_CHECKER_FAILURE_RETRIES
            value: "1"
{{- if .Values.uptimeChecker.env }}
{{ toYaml .Values.uptimeChecker.env | indent 8 }}
{{- end }}
{{- if .Values.uptimeChecker.existingSecretEnv }}
        envFrom:
        - secretRef:
            name: {{ .Values.uptimeChecker.existingSecretEnv }}
{{- end }}
{{- if .Values.uptimeChecker.volumeMounts }}
{{ toYaml .Values.uptimeChecker.volumeMounts | indent 8 }}
{{- end }}
{{/*{{- if .Values.uptimeChecker.livenessProbe.enabled }}*/}}
{{/*        livenessProbe:*/}}
{{/*          periodSeconds: {{ .Values.uptimeChecker.livenessProbe.periodSeconds }}*/}}
{{/*          initialDelaySeconds: {{ .Values.uptimeChecker.livenessProbe.initialDelaySeconds }}*/}}
{{/*          timeoutSeconds: {{ .Values.uptimeChecker.livenessProbe.timeoutSeconds }}*/}}
{{/*          failureThreshold: {{ .Values.uptimeChecker.livenessProbe.failureThreshold }}*/}}
{{/*          exec:*/}}
{{/*            command:*/}}
{{/*              - rm*/}}
{{/*              - /tmp/health.txt*/}}
{{/*{{- end }}*/}}
        resources:
{{ toYaml .Values.uptimeChecker.resources | indent 12 }}
{{- if .Values.uptimeChecker.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.uptimeChecker.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.uptimeChecker.sidecars }}
{{ toYaml .Values.uptimeChecker.sidecars | indent 6 }}
{{- end }}
{{- if .Values.global.sidecars }}
{{ toYaml .Values.global.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-uptime-checker
      {{- end }}
      {{- if .Values.uptimeChecker.priorityClassName }}
      priorityClassName: "{{ .Values.uptimeChecker.priorityClassName }}"
      {{- end }}
      volumes:
      - name: uptime-checker-storage
        emptyDir: {}
{{- if .Values.uptimeChecker.volumes }}
{{ toYaml .Values.uptimeChecker.volumes | indent 6 }}
{{- end }}
{{- if .Values.global.volumes }}
{{ toYaml .Values.global.volumes | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
