{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-nginx
data:
  server-block.conf: |
    upstream relay {
      server {{ template "sentry.fullname" . }}-relay:{{ template "relay.port" }};
    }

    upstream sentry {
      server {{ template "sentry.fullname" . }}-web:{{ template "sentry.port" }};
    }

    server {
      listen {{ template "nginx.port" }};

      proxy_redirect off;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      location /api/store/ {
        proxy_pass http://relay;
      }

      location ~ ^/api/[1-9]\d*/ {
        proxy_pass http://relay;
      }

      location / {
        proxy_pass http://sentry;
      }
    }
{{- end }}
